
public enum InputEventsType {
    setNickname,
    setGameMode,
    setMap,
    setStartingSkull,
    setBot,
    setFinalFrenzy,
    readyToPlay,
    chooseSpawningPowerUp,
    chooseAction,
    moveChooseSquare,
    GrabStuffChooseSquare,
    GrabStuffChooseWeapon,
    GrabStuffChooseHowToPay,
    ShootPeopleChooseSquare,
    ShootPeopleChooseWeapon,
    ShootPeopleChooseTarget,
    ShootPeopleChooseEffect,
    ReloadYN,
    ReloadChooseWeapon,
    ReloadHowToPay,
    ChoosePowerUp,
    etc...
}